sudo: required
services:
  - docker

script:
  - make build

after_script:
  - sudo chown -R travis dist
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
      make release USER_NAME=deploy-travis USER_EMAIL=deploy-travis;
    fi'
